# Generated by Django 5.0.6 on 2024-06-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='was_online_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
