# Generated by Django 5.0.6 on 2024-07-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_friends_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='user',
            name='was_online_at',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
