# Generated by Django 5.0.6 on 2024-07-09 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField()),
                ('status', models.CharField(choices=[('pend', 'Pending'), ('deliv', 'Delivered'), ('prog', 'In Progress')], default='pend', max_length=10)),
                ('deliver_to', models.CharField(max_length=999)),
                ('owner', models.ForeignKey(default='Anonymous user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
